// This file was generated by RedwoodJS
import * as Cell from './PostsCell'
import type { CellProps } from '@redwoodjs/web'
import type { POSTS, POSTSVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PostsCell'

type CellInputs = CellProps<SuccessType, POSTS, typeof Cell, POSTSVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
