// This file was generated by RedwoodJS
import * as Cell from './ArticleCell'
import type { CellProps } from '@redwoodjs/web'
import type { ArticleQuery, ArticleQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ArticleCell'

type CellInputs = CellProps<SuccessType, ArticleQuery, typeof Cell, ArticleQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
