// This file was generated by RedwoodJS
import * as Cell from './CommentsCell'
import type { CellProps } from '@redwoodjs/web'
import type { CommentsQuery, CommentsQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CommentsCell'

type CellInputs = CellProps<SuccessType, CommentsQuery, typeof Cell, CommentsQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
