// This file was generated by RedwoodJS
import AboutPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/AboutPage/AboutPage'
import ArticlePageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/ArticlePage/ArticlePage'
import ContactPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/ContactPage/ContactPage'
import FatalErrorPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/HomePage/HomePage'
import LoginPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/SignupPage/SignupPage'
import PostEditPostPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/home/nese/cs490-hw3/redwood-tutorial/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const AboutPage: typeof AboutPageType
  const ArticlePage: typeof ArticlePageType
  const ContactPage: typeof ContactPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}
