// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    login: (params?: RouteParams<"/login"> & QueryParams) => "/login"
    signup: (params?: RouteParams<"/signup"> & QueryParams) => "/signup"
    forgotPassword: (params?: RouteParams<"/forgot-password"> & QueryParams) => "/forgot-password"
    resetPassword: (params?: RouteParams<"/reset-password"> & QueryParams) => "/reset-password"
    newPost: (params?: RouteParams<"/admin/posts/new"> & QueryParams) => "/admin/posts/new"
    editPost: (params?: RouteParams<"/admin/posts/{id:Int}/edit"> & QueryParams) => "/admin/posts/{id:Int}/edit"
    post: (params?: RouteParams<"/admin/posts/{id:Int}"> & QueryParams) => "/admin/posts/{id:Int}"
    posts: (params?: RouteParams<"/admin/posts"> & QueryParams) => "/admin/posts"
    contact: (params?: RouteParams<"/contact"> & QueryParams) => "/contact"
    article: (params?: RouteParams<"/article/{id:Int}"> & QueryParams) => "/article/{id:Int}"
    about: (params?: RouteParams<"/about"> & QueryParams) => "/about"
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
  }
}

