// This file was generated by RedwoodJS
import * as Cell from './PostCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindPostById, FindPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './PostCell'

type CellInputs = CellProps<SuccessType, FindPostById, typeof Cell, FindPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
