// This file was generated by RedwoodJS
import * as Cell from './ArticlesCell'
import type { CellProps } from '@redwoodjs/web'
import type { ArticlesQuery, ArticlesQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ArticlesCell'

type CellInputs = CellProps<SuccessType, ArticlesQuery, typeof Cell, ArticlesQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
